version: '3'
services:
# DB
  db:
    container_name: go-jwt-db
    image: postgres:13.4
    environment: 
      - POSTGRES_PASSWORD=${DB_PW}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes: 
      - "./docker/data/:/docker-entrypoint-initdb.d/"
    networks:
      - go
# API
  golang:
    container_name: go-jwt-api
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/go/src
    environment: 
      - POSTGRES_PASSWORD=${DB_PW}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - TEMPLATE_PATH=/go/src
    tty: true
    depends_on:
      - db
    networks:
      - go
# FrontEnd
  apache:
    container_name: go-jwt-web
    build: ./docker/apache/.
    ports:
      - 80:80
    volumes:
      - ./static_server/:/var/www/html/

networks:
  go:
    driver: bridge
